- hosts: test
  become: yes
  tasks:
     - name: execute the pythonscript
       command: '162.70.211.66/ansible/samplepython.py'
       register: find_output
     - debug:
          var: find_output
